### ISSUE TITLE
Missing Kak Crate

### ISSUE THREAD

**Issue by KankuroGB** [mracsys/tootr#38]
Kak is missing the adult crate by the beggar, right below the Bazaar; which would total to 3 crates to check in Kak. 

Not sure if this is only on a specific branch or not though, noticed it on Fenhl's branch.

**Comment by mracsys** [comment]
There are only two shuffled crates per the list in the main fork: https://github.com/OoTRandomizer/OoT-Randomizer/blob/ae1a3908ccfc37af88297eac6383b74217f6b519/LocationList.py#L409-L410

Right now I'm tracking the main fork and Roman's fork, with additional features either already PR'd or likely to be PR'd to main. Fenhl's fork moves too quickly for me to keep up.
