### ISSUE TITLE
[Suggestion] Multiple "Profiles"?

### ISSUE THREAD

**Issue by KankuroGB** [mracsys/tootr#39]
Could the ability to have multiple profiles/seeds be added? I'm asking because I tend to play solo and with friends, but unless I do incognito or use a different browser (which I'd much rather not have to do) I'm not able to do more than a single seed. This wouldn't be a problem, but since friends don't always have the ability to do a seed in a single setting and my personal seeds are getting more and more complex, resulting in more and more time being required to beat them, I'd love to be able to just have a dropdown or something to swap between my seeds (kinda like presets with the generators).

**Comment by mracsys** [comment]
This is a good idea. I'll add it to the list for after the rewrite.

**Comment by mracsys** [comment]
I've added this in 1.0. In the File menu, select Save to open a menu where you can name your current tracked game. Select Load from the File menu to find and restore it later.

Sorry this took so long!
