### ISSUE TITLE
Make an option to allow some special locations with small checks to be visible with reduced view

### ISSUE THREAD

**Issue by alkalineace** [mracsys/tootr#40]
Some locations that don't have any checks are still important to keep in mind (especially in RSL).

An option to allow these special locations to be always displayed (even if we mask checks already done) would help in keeping notes of those.

These locations are : 
- Dampe's Hut (for Light Arrows hint in RSL and other misc hints) -> you cannot collect this hint as child
  --> currently in the House list, if accepted this could be its own Interior
- Sleeping Talon House -> you cannot initiate the trade without pocket cucoo
- Granny's Potion Shop -> (if expensive merchants is off) you cannot initiate the trade without odd potion
- Mask Shop -> you need to swap masks several times to do the checks

**Comment by mracsys** [comment]
Thanks for the suggestion! This is on my list after the refactor. I'm looking at two implementations:

1. Option to show secondary locations tied to a "real" location. The secondaries would be hidden after all linked primaries are checked, and they would not count towards check total.
2. Global location search to filter the view for matching locations. This is more for things like Great Fairy Fountains that can be difficult to route currently if they are spread out in the UI.

Dampe's Hut will be included with hint tracking (#5) when that is implemented.

**Comment by alkalineace** [comment]
1. This is way better than my suggestion, seems awesome
2. Also really good to know it will come. Right now, my best friend is CTRL-F (hence why i made this suggestion, it's hard to find hidden things)

Glad to know Hint Tracking is on todo ; friends still have trouble with some gossip stone locations sometimes.

**Comment by mracsys** [comment]
For now this was included in #46 as a new "Show Helpful Extra Checks" option in the Tracker Settings menu. It also includes bean planting, unshuffled trade events, setting scarecrow's song, and saving Epona.

I'm leaving this open to make sure this is complete for the rewrite.

**Comment by mracsys** [comment]
There is a new "Show Unshuffled Locations" tracker setting that lets you always show certain categories of locations, including trade quest turn ins. There is a separate Show Hints option for the gossip stones, and each stone can be assigned a hint that automatically colors regions. Blue is WOTH, Green plus an item in the title bar is Path, Grey is Foolish.
