### ISSUE TITLE
Color the lines of special locations & Mark an area as a goal

### ISSUE THREAD

**Issue by alkalineace** [mracsys/tootr#41]
In Mixed Pools, it can become tedious to find back a dungeon location (you have to go to the dungeon tab to check that).
While not being a huge problem, it actually becomes an issue for Bosses Mixed Pools. There is no built-in way to quickly eyeball the bosses locations.
Exemple : Barinade is at remote Southern Grotto, but i forgot that.

Additionnally, you're hinted every region a boss is in - but there is no built-in way to mark that in the tracker.

Here are the proposed suggestions : 

1. Color the lines of important checks
- The dungeons marked in a location would have the background of their line be a specific color, and the bosses marked in a location would have another specific color
- I don't think it's necessary to mark other types of locations, but it could be expended

2. Add a way to mark a location as a goal
- Left-clicking on an area in the location would increment a counter there, and right-clicking would decrement it
- The counter would help to track bosses locations (the most useful one), or even WOTH locations/major number count - user can be creative, it's basically an additionnal way to take note
- The counter could be placed there for example :
![image](https://github.com/mracsys/tootr/assets/7566908/aab3471f-dede-4a1a-b465-ec7d1b0f6909)

**Comment by mracsys** [comment]
Areas marked via a path hint gossip stone will have a green background and an icon for the path in the title bar similar to your screenshot.

I did not add any special coloring for dungeon or boss entrances. The new search tool should help with this. Let me know if you'd like to see something different!
