### ISSUE TITLE
Cannot track main exit of dungeon found from boss

### ISSUE THREAD

**Issue by fenhl** [mracsys/tootr#42]
If a dungeon is entered through the boss door, there is currently no way to mark where the dungeon's front entrance leads to.

**Comment by mracsys** [comment]
Can you provide an example? I was able to link front entrances after linking to the in through the boss room both by linking to the front entrance and by manually swapping to the dungeon view and linking the front from there. There is a bug with the URLs not swapping to dungeon view if they go through the back, I'll get a fix out for that.

**Comment by fenhl** [comment]
I checked again and the actual bug seems to be that the front exits of dungeons are hidden if “Show Locations” is off.

**Comment by mracsys** [comment]
1.0 fixes this issue by throwing out the old region/entrance visibility algorithm. Region/entrance visibility is now handled with tags added by the logic search backend. Users can override if they want to ignore logic and show everything.
