### ISSUE TITLE
Treasure Chest Game Keysanity

### ISSUE THREAD

**Issue by alkalineace** [mracsys/tootr#44]
The Treasure Chest Game Keysanity mode is not handled right now.

It should probably be an option like Thieves's Hideout.

The checks that need to be added : 
- Merchant key
- First room left chest
- First room right chest
- Second room left chest
- Second room right chest
- Third room left chest
- Third room right chest
- Fourth room left chest
- Fourth room right chest
- Fifth room left chest
- Fifth room right chest

The check that needs to be renamed : 
- Treasure chest game reward -> Final room chest

The item list does not have a way to indicate a Treasure Chest Game smallkey either.

**Comment by mracsys** [comment]
It's on the list for the refactor. There's a lot coming in it that will make maintenance easier. Not to discourage you or anyone from raising these issues, please keep them coming :smile:

**Comment by 3pacgangstarap** [comment]
fixed in #46 if you decide to merge it

**Comment by mracsys** [comment]
Merged with #46
