### ISSUE TITLE
Show Impa's cow in both regions

### ISSUE THREAD

**Issue by fenhl** [mracsys/tootr#49]
Impa's cow is logically reachable from the front, so the check should be displayed there as well, especially if the back entrance hasn't been found yet.

**Comment by mracsys** [comment]
Already done in the rewrite. ETA Soon(tm). Other stuff has been getting in the way.

**Comment by mracsys** [comment]
Added in 1.0. Also works for other connectors like Kak Potion Shop back, Dampe's Grave -> Windmill, etc.
