### ISSUE TITLE
Wrong value for `shopsanity` setting in preset

### ISSUE THREAD

**Issue by fenhl** [mracsys/tootr#50]
If I set the randomizer version to 8.1.51 Fenhl-1 and create a new file from the “Fenhl's Casual” preset, the “Shuffle Shops” setting is set to “Off”. In the actual preset, it's set to `random`: https://github.com/fenhl/OoT-Randomizer/blob/032f3a95acfed7f431fe6c5125aa44438ca6d6d0/data/presets_default.json#L96

**Comment by mracsys** [comment]
`random` values are removed from presets to avoid issues with non-deterministic settings (see https://github.com/mracsys/randomizer-graph-tool/blob/47369303ab85f9103f52d2a19cef9d88bd40749b/src/plugins/ootr-latest/SettingsList.ts#L733-L746), although shopsanity was not supposed to be caught in this. It's an easy fix, should be available in the next 10-15 minutes.
